#!/bin/bash

SCRIPT_PATH=$( cd $(dirname $0) ; pwd -P )

DATE=$(date '+%Y-%m-%d_%H:%M:%S')
BACKUP_DIR="backup-$(date +%s)"

cd $SCRIPT_PATH
mkdir $BACKUP_DIR

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [[ -d $line ]]
    then
	    echo "saving data from path: $line"
	    cp -r $line $BACKUP_DIR
    else
	    echo "path: $line is not a directory"
    fi
done < "directories"

if [ -z "$(ls -A $BACKUP_DIR)" ]; then
	echo "nothing to backup"
else
	echo "Not Empty"
	zip -r $BACKUP_DIR-$DATE.zip $BACKUP_DIR
fi

rm -rf $BACKUP_DIR
