#!/bin/bash

TAG_LOG="BACKUP-TOOL"
SCRIPT_PATH=$( cd $(dirname $0) ; pwd -P )

DATE=$(date '+%Y-%m-%d_%H:%M:%S')
BACKUP_DIR="backup-$(date +%s)"

cd $SCRIPT_PATH
mkdir $BACKUP_DIR

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [[ -d $line ]]
    then
	    echo "$TAG_LOG: saving directory $line"
	    cp -r $line $BACKUP_DIR
    else
	    echo "$TAG_LOG: unable to find directory $line"
    fi
done < "directories"

if [ -z "$(ls -A $BACKUP_DIR)" ]; then
	echo "$TAG_LOG: nothing found to backup"
else
	echo "$TAG_LOG: zipping all backup into $BACKUP_DIR-$DATE.zip file"
	zip -r $BACKUP_DIR-$DATE.zip $BACKUP_DIR
fi

rm -rf $BACKUP_DIR
